### ISSUE TITLE
Settings Menu Icons are Off by One

### ISSUE THREAD

**Issue by JakeCover** [ClearVision/ClearVision-v6#10]
First off, thanks for the great work, I'm so glad that this exists!

I noticed that the icons for some of the settings seem to be off. As you can see in the screenshot below, they match up until discord nitro, but then other icons are for the button below them, with the server boost icon on gift inventory, hype squad on server boost, etc. The betterdiscord settings still have the right icons though. Seems like discord added one of these things recently, probably gift inventory, as nox had this issue as well.

Examples (see how the later icons are off by one but the betterdiscord ones are fine?)

![image](https://user-images.githubusercontent.com/22972550/82738979-de119600-9cf0-11ea-95ca-c7f8434001d9.png)
![image](https://user-images.githubusercontent.com/22972550/82738987-ea95ee80-9cf0-11ea-9fe8-1919d0fbd1e8.png)

**Comment by untuned** [comment]
+1
happens to me too, they added new entries and whenever that happens the list will break
