### ISSUE TITLE
[Bug Report] Video Call & Screen Share Button broken

### ISSUE THREAD

**Issue by reynoldyehezkiel** [ClearVision/ClearVision-v6#106]
### Did You Search Other Issues?

- [x] I have checked other issues

### Does This Bug Show On The Default Theme?

- [X] I have reproduced this on the default theme

### Describe The Bug

The button is broken when video call and screen share are disabled

### Reproduction Steps

```bash
1. Go to voice channel with video call and screen share button disabled
```

### Screenshots

```bash
https://user-images.githubusercontent.com/73789263/173008807-a4c08d51-3920-4b44-883d-705da2ee567c.png
```

**Comment by Leozard** [comment]
We'll look into it

**Comment by Leozard** [comment]
Should be fixed

**Comment by reynoldyehezkiel** [comment]
it's better now, thanks
![Screenshot 2022-06-22 152043](https://user-images.githubusercontent.com/73789263/174980594-b6d24e63-8193-401a-ac7a-ea9c56f8ff9b.png)
