### ISSUE TITLE
[Feature Request] Add a setting to change header fonts seperately to main font.

### ISSUE THREAD

**Issue by StarrKiss** [ClearVision/ClearVision-v6#107]
### Did You Search Other Suggestions?

- [x] I have checked if this feature request exists already

### Is your feature request related to a problem?

I want to change header fonts, ie, channel names at the top, settings panel, etc into a different font than the main UI font.

### Screenshots and/or description of the feature request.

![image](https://user-images.githubusercontent.com/13007697/173731332-8ac97dd3-78a8-4207-bb4d-41bd799957c1.png)
fonts like this could be distinct from other fonts.

### Why does the theme need this?

It would look a lot better and aesthetically match the rest of my PC.

**Comment by Leozard** [comment]
We won't add a feature just to cater to 1 person. You can add code in the file to change the header font. Join our discord if u need help on how to do it
