### ISSUE TITLE
[Bug Report] Role styles are no longer working

### ISSUE THREAD

**Issue by xchatiii** [ClearVision/ClearVision-v6#108]
### Did You Search Other Issues?

- [X] I have checked other issues

### Does This Bug Show On The Default Theme?

- [X] I have reproduced this on the default theme

### Describe The Bug

Roles (or whatever it is called) no longer looks like what it used to be, and are reset to the original styles.

I have already tried restarting Discord, removing all plugins and other themes and using the default settings.

### Reproduction Steps

```bash
1. Click on a user on the user list
2. Look at the role styles
3. Cry
```

### Screenshots

![sTa6U3G](https://user-images.githubusercontent.com/69412273/178142251-d6895f82-9e49-4be8-a823-cccb43461408.png)

**Comment by NyxIsBad** [comment]
Fixed 👍

**Comment by xchatiii** [comment]
Not fixed. Newest commit does something like this.

![image](https://user-images.githubusercontent.com/69412273/181449693-7cd96ab4-d9c7-4aea-893f-732e76852193.png)

Note the barely visible role remove button, which requires professional pixel-perfect precision cursor handling.

The workaround in the Discord server removes the role remove button altogether, so I will have to stick with the bug for a bit longer.

**Comment by NyxIsBad** [comment]
> Not fixed. Newest commit does something like this.
> 
> ![image](https://user-images.githubusercontent.com/69412273/181449693-7cd96ab4-d9c7-4aea-893f-732e76852193.png)
> 
> Note the barely visible role remove button, which requires professional pixel-perfect precision cursor handling.
> 
> The workaround in the Discord server removes the role remove button altogether, so I will have to stick with the bug for a bit longer.

No, it is fixed. It's just that gitlab is broken and not mirroring the commits.

**Comment by xchatiii** [comment]
Alrighty, compiled it manually and it works. Thanks for your work.

**Comment by NyxIsBad** [comment]
Hopefully gitlab stops being dumb soon ;-;
