### ISSUE TITLE
[Bug Report] Voice channels and unread flickering

### ISSUE THREAD

**Issue by Benomat** [ClearVision/ClearVision-v6#109]
### Did You Search Other Issues?

- [X] I have checked other issues

### Does This Bug Show On The Default Theme?

- [x] I have reproduced this on the default theme

### Describe The Bug

When using ClearVision Voice channel names and many more texts are flickering. This also happening with default settings of the theme. I don't have this issue with any other themes nor without themes.

### Reproduction Steps

```bash
1. Just gotta watch closely. It is pretty hard to see with the default color set.
2. It happens faster when hovering over messages so I guess it is related to something updating
```

### Screenshots

It's not visible on screenshots but I made 2 videos to show it:
You can see it very good [here](https://benomat3000.web.app/cdn/ClearVision/visible.mp4)
With default theme [here](https://benomat3000.web.app/cdn/ClearVision/Default_Settings.mp4)

**Comment by Benomat** [comment]
I found what was causing the issue in the main.css file and removed the part causing it. This fixed it.
[your original css](https://benomat3000.web.app/cdn/ClearVision/original.css) ->  [fixed version of that](https://benomat3000.web.app/cdn/ClearVision/main_fixed_small.css)
[readable unfixed version](https://benomat3000.web.app/cdn/ClearVision/original_readable.css) -> [fixed readable](https://benomat3000.web.app/cdn/ClearVision/main_fixed.css)
You can see the changes I made [here](https://www.diffchecker.com/0DPqTMLJ)

**Comment by NyxIsBad** [comment]
I can't reproduce this after 2 days of testing. Can anyone else on the team reproduce?

**Comment by NyxIsBad** [comment]
Leo couldn't reproduce, and suggested that this seems like this might be an Electron bug (the platform that Discord is written on), and only occurs occasionally by triggers unassociated with the theme. If this comes up again in the future though, I'll look further into it. Thanks for the issue report!
