### ISSUE TITLE
[Bug Report] Image embeds via URL not correctly sized

### ISSUE THREAD

**Issue by Satoru-1816** [ClearVision/ClearVision-v6#111]
### Did You Search Other Issues?

- [X] I have checked other issues

### Does This Bug Show On The Default Theme?

- [X] I have reproduced this on the default theme

### Describe The Bug

A few days ago, after restarting Discord all the GIF embeds are wider than they should be. This is especially annoying when sending GIFs or emojis (in .gif format). This doesn't happen in Discord's default theme though, but it does in ClearVision's original theme.

**Update**: 
I noticed it also happens when sending image URLs, so that's probably the main issue. JPGs, PNGs and GIFs alike.

### Reproduction Steps

```bash
1. Send any URL containing an image or GIF
2. See the embed not correctly sized
```

### Additional Context

![BUG_1](https://user-images.githubusercontent.com/81326989/182653918-cc95720b-308d-4cb4-9088-6aa01ace5662.png)
![BUG_2](https://user-images.githubusercontent.com/81326989/182653942-43e764b4-f4ab-4daf-a6c5-3b41033a27e6.png)

**Comment by NyxIsBad** [comment]
This is a discord design change, and not an issue with the theme. I have, however, remediated this.
