### ISSUE TITLE
[Bug Report] The Settings button texture.

### ISSUE THREAD

**Issue by RedixWasTaken** [ClearVision/ClearVision-v6#112]
### Did You Search Other Issues?

- [X] I have checked other issues

### Does This Bug Show On The Default Theme?

- [X] I have reproduced this on the default theme

### Describe The Bug

The settings button has been cut off like half the texture is missing because of the new discord update.

### Reproduction Steps

```bash
1. Your mini profile where the settings are in the left bottom corner.
```

### Screenshots

```bash
https://freeimage.host/i/UHqbLX (I don't know how to upload an image so I give you a link)
```

**Comment by ABadNameSniper** [comment]
Especially noticeable with the GameActivityToggle plugin

**Comment by NyxIsBad** [comment]
Fixed for vanilla, but not for gameactivitytoggle. I'll see if there's an easy way to do it, but it seems impossible to have both right now
