### ISSUE TITLE
[Bug Report] Settings button disappears with GameActivityToggle

### ISSUE THREAD

**Issue by raptor1820** [ClearVision/ClearVision-v6#114]
### Did You Search Other Issues?

- [X] I have checked other issues

### Does This Bug Show On The Default Theme?

- [X] I have reproduced this on the default theme

### Describe The Bug

The settings button disappears when the plugin GameActivityToggle by DevilBro is enabled. The settings button was showing up until the latest discord update where the user modal can be accessed from the bottom.

### Reproduction Steps

```bash
1. Install and enable the plugin GameActivityToggle by DevilBro
2. Enable clear vision
```

### Additional Context

This is not an issue with GameActivityToggle as the settings button was showing up with other themes/when themes were disabled
Uploading images here as the screenshots section did not allow me to add pictures.

with default Clearvision (the button is hidden)
![image](https://user-images.githubusercontent.com/57589076/183581043-712861b9-d262-4296-8c5f-2b6b4db583b9.png)

Themes disabled
![image](https://user-images.githubusercontent.com/57589076/183580878-ab475275-5518-4124-b807-276f9bd6a69a.png)

**Comment by Leozard** [comment]
We do not actively support plugins. A workaround is to increase the channel width variable in the file
