### ISSUE TITLE
[Bug Report] The profile colour/background.

### ISSUE THREAD

**Issue by Xann-y** [ClearVision/ClearVision-v6#119]
### Did You Search Other Issues?

- [X] I have checked other issues

### Does This Bug Show On The Default Theme?

- [X] I have reproduced this on the default theme

### Describe The Bug

Once again, Discord messed up the theme by doing an update.
The profile colour is now the ugly grey as it was before.
<img width="107" alt="Screen Shot 2022-09-21 at 20 22 56" src="https://user-images.githubusercontent.com/112470384/191454257-6ded7f4a-a713-437d-9625-fc63037bca8a.png">
<img width="578" alt="Screen Shot 2022-09-21 at 20 22 08" src="https://user-images.githubusercontent.com/112470384/191454263-35447be6-175e-41c9-ae6e-b510f7571a31.png">
<img width="559" alt="Screen Shot 2022-09-21 at 20 18 08" src="https://user-images.githubusercontent.com/112470384/191454272-42a8b884-32f5-4bb2-8bb6-fafb1d59c7a0.png">

as you can see i am on the latest version of ClearVision

### Reproduction Steps

```bash
1. Click on anyone's profile. 
2. Although some people have a different style of background. It matches with the banner that they have. 
3.
...
```

### Additional Context

screw u discord

**Comment by AzukiiMochi** [comment]
![image](https://user-images.githubusercontent.com/72458125/192153395-d2179e5a-5ab2-477b-b269-9deddfe20265.png)

same here, greyed profiles

**Comment by AzukiiMochi** [comment]
![image](https://user-images.githubusercontent.com/72458125/192153483-43bc7f39-66d7-46aa-a7d3-6f7881cdf14f.png)
same here, greyed out profiles

**Comment by GAbO1254** [comment]
Issue still persists
![image](https://i.imgur.com/ACkMXae.png)

**Comment by Leozard** [comment]
only a handfull of people received this new profile, and unfortunately I don't have it and the staff that got that update has been really busy lately.
