### ISSUE TITLE
Slight issue of the skin in combination with the BetterRoleColors plugin

### ISSUE THREAD

**Issue by DUSKvsDAWN** [ClearVision/ClearVision-v6#120]
So I got an update for both BetterRoleColors (plugin) and the version of the skin today. However, there seems to be a slight issue with the two combined, and I'm not entirely sure if it should be posted here, or if I should let the devs of BetterRoleColor know. The plugin works just fine with no skin applied. However, when I apply any version of the Clearvision skin (either the v6 Beta or 6.3) the color of the stripes next to the role name in the member list do not match. They do, however, start matching once I hover over the stripe on whatever side (doesn't matter if it's left or right). So I was wondering why the colors seem to be a bit wonky combined with the skin. I tried older and newer versions of skins, I modified BetterRoleColors a bit but that doesn't seem to help. I was wondering if this is a skin issue, and if so, if you guys can help :)

**Comment by untuned** [comment]
Please recreate this issue using the bug report form.
