### ISSUE TITLE
[Bug Report] Issue Description

### ISSUE THREAD

**Issue by Only1337** [ClearVision/ClearVision-v6#121]
### Did You Search Other Issues?

- [X] I have checked other issues

### Does This Bug Show On The Default Theme?

- [X] I have reproduced this on the default theme

### Describe The Bug

uhmmm...

### Reproduction Steps

```bash
1. View profile
2. 
3.
...
```

### Additional Context

![image](https://user-images.githubusercontent.com/47225461/197832261-0090b235-b094-4f7a-b033-9e8274fc0a6c.png)
![Discord_pFtbkGgI9u](https://user-images.githubusercontent.com/47225461/197832285-60d6d2ca-ccea-4609-9b95-2b1900133047.png)

**Comment by Xann-y** [comment]
So yea if u actually searched the other issues then you'd have seen that I've already opened an issue talking about the same thing. 

Just a heads up.

**Comment by Xann-y** [comment]
Also it seems to be fixed now

**Comment by Only1337** [comment]
> Also it seems to be fixed now


https://user-images.githubusercontent.com/47225461/198584759-355883c9-82c4-4e3d-a930-8533e3e8c9f8.mp4

**Comment by Xann-y** [comment]
its some perk the nitro's get
