### ISSUE TITLE
[Bug Report] username is cutted

### ISSUE THREAD

**Issue by BlueStarBRS** [ClearVision/ClearVision-v6#123]
### Did You Search Other Issues?

- [X] I have checked other issues

### Does This Bug Show On The Default Theme?

- [X] I have reproduced this on the default theme

### Describe The Bug

no matter how big or small I make my discord (with strg +/-) my name is always unnecessarily cut off but it wasn't always like that

### Reproduction Steps

```bash
idk ? use v6 clear vission in this acually situation from unnecessary breaking DS updates
and have a name like my one ?
```

### Screenshots

```bash
screenshots in additional context
```

### Additional Context

how my one looks with clearvision:
![image](https://user-images.githubusercontent.com/25110093/200706639-8dcb4c4f-33fb-4d21-bb10-f93d95dcf641.png)

how it have to be (example with other themes:
![image](https://user-images.githubusercontent.com/25110093/200706684-31dd85b2-2198-4328-9bd4-bfcca9c73c8c.png)
or like that;
![image](https://user-images.githubusercontent.com/25110093/200706706-bf19e19f-d148-4de9-9b55-39664ec760f3.png)
![image](https://user-images.githubusercontent.com/25110093/200723876-0f923078-452b-4247-8763-d9fb9e8b3a6d.png)
or like that from stock DS:
![image](https://user-images.githubusercontent.com/25110093/200706981-0fa0a1f9-7965-4608-a205-4717a86711fa.png)

my name can fit in this but it dosn´t :/
+with the animation issue (look other bug report) its rly feel not good and is anoying

**Comment by NyxIsBad** [comment]
This doesn't show as a bug and instead is a product of design choice with margins and a second applied theme other than clearvision (radial status). We won't change the theme to suit individual needs, but you can join the server and open a custom css ticket if you want custom fixes.
