### ISSUE TITLE
[Bug Report] Background be gone

### ISSUE THREAD

**Issue by ColonelGerdauf** [ClearVision/ClearVision-v6#126]
### Did You Search Other Issues?

- [X] I have checked other issues

### Does This Bug Show On The Default Theme?

- [X] I have reproduced this on the default theme

### Describe The Bug

The theme background is not functional

### Reproduction Steps

```bash
1. install BetterDiscord
2. install ClearVision
3. (optional) use a background image where the URL works.
```

### Additional Context

 This is apparently due to Discord experimenting with customization.

**Comment by littlepriceonu** [comment]
yea, same here. Remade my theme with the theme editor to see if it was just my theme being old but it wasn't.

**Comment by Elijah5735823** [comment]
I also have this error, I have changed the image too and still isn't working.

**Comment by Loki-101** [comment]
I have this problem as well.

**Comment by NyxIsBad** [comment]
Fixed, please check/join discord for more documentation
