### ISSUE TITLE
[Bug Report] Jerky scrolling

### ISSUE THREAD

**Issue by LewisPattJr** [ClearVision/ClearVision-v6#129]
### Did You Search Other Issues?

- [X] I have checked other issues

### Does This Bug Show On The Default Theme?

- [x] I have reproduced this on the default theme

### Describe The Bug

Since the recent issue with BetterDiscord crashing immediately on startup was fixed with a new .asar from BD, scrolling through channels with embedded media (images, videos, etc.) stutters while ClearVision is enabled (the scroll position jumps back a large amount for every image loaded).  This seems to occur only when the images are initially loaded; scrolling back through already loaded images is smooth.

This only happens when ClearVision is loaded; using other themes or no theme at all gets rid of the issue.

### Reproduction Steps

```bash
1. Use BetterDiscord version 1.9.1.
2. Enable ClearVision theme.
3. Locate a channel with many image posts.
4. Try to scroll through the posts.
```

**Comment by Leah96xxx** [comment]
Can confirm it happens for me to in channels with unread messages

**Comment by nymphlode** [comment]
Same here, can't scroll up without it sending me backwards .Have to really fight it to scroll.

**Comment by NyxIsBad** [comment]
Currently open ticket in the support server as well, thanks for letting me know

**Comment by NyxIsBad** [comment]
fixed
