### ISSUE TITLE
[Bug Report] Theme does not override custom coloured profiles

### ISSUE THREAD

**Issue by EdVraz** [ClearVision/ClearVision-v6#132]
### Did You Search Other Issues?

- [X] I have checked other issues

### Does This Bug Show On The Default Theme?

- [X] I have reproduced this on the default theme

### Describe The Bug

When clicking on a profile with custom colours (nitro), the colour is displayed instead of the custom background expected by the plugin.

### Reproduction Steps

```bash
1. Have the theme enabled
2. Click on a user with nitro who has a custom-coloured theme
3. See the coloured profile pop-out instead of the image of the theme
...
```

### Screenshots

```bash
nitro profile: https://prnt.sc/06gO9W9Hy0Tt
normal profile: https://prnt.sc/3TQ03OU3seOE
```

**Comment by EdVraz** [comment]
This also applies to the full user popout 

https://prnt.sc/zk8E5aaUM1rW
https://prnt.sc/Oau0eKuid_he

(same with default, was too lazy to change themes rn)

**Comment by Leozard** [comment]
That's intended so everyone can show off their custom profiles

**Comment by EdVraz** [comment]
Alright, I wasn't sure if that was the case, thanks for the clarification
