### ISSUE TITLE
[Bug Report] Issue Description

### ISSUE THREAD

**Issue by RevaluesL** [ClearVision/ClearVision-v6#134]
### Did You Search Other Issues?

- [X] I have checked other issues

### Does This Bug Show On The Default Theme?

- [X] I have reproduced this on the default theme

### Describe The Bug

whenever it launches it makes people that are offline apear as online
i'm using vancord so i dont know if thats the problem but please help

### Reproduction Steps

```bash
1.on discord with vancord go to the "vancord" tab
2.on quick actions paste the css code from the github file
```

### Screenshots

```bash
https://imgur.com/a/ycYK2aH
```

**Comment by NSore** [comment]
Also having this issue.

**Comment by NyxIsBad** [comment]
There is an open issue regarding this on the support server, so I will close the issue on github, please direct discussion there

**Comment by NyxIsBad** [comment]
https://canary.discord.com/channels/212324635356692500/1105427830046728192/1105517180445011988
Please refer to these messages, it seems unrelated to theme. Check for plugins or injector/openasar settings
