### ISSUE TITLE
[Bug Report] Issue Description

### ISSUE THREAD

**Issue by unholypersona** [ClearVision/ClearVision-v6#135]
### Did You Search Other Issues?

- [X] I have checked other issues

### Does This Bug Show On The Default Theme?

- [X] I have reproduced this on the default theme

### Describe The Bug

changing --user-modal-position: and --user-modal-size: in /* USER POPOUT BACKGROUND */ does nothing

### Reproduction Steps

```bash
1. go to themes
2. press edit
3. go to /* USER POPOUT BACKGROUND */
4. change --user-modal-position: from --user-modal-position: var(--background-position); to  --user-modal-position: center or var(--background-position); to var(center);
5. repeat the same for --user-modal-size: but with cover instead
```

### Screenshots

```bash
expected result:
https://github.com/ClearVision/ClearVision-v6/assets/113929815/dc6f0fbd-39b0-40e5-b358-1b1a7111194c

actual result:
https://github.com/ClearVision/ClearVision-v6/assets/113929815/14669823-569c-44b8-97fd-cc2aa6b936e6
```

**Comment by Leozard** [comment]
Uh that changes the modal, the image you sent is the popout. example:
![image](https://github.com/ClearVision/ClearVision-v6/assets/26217384/726d5c83-6a16-4042-ab8d-9c56957cb4c6)

var(center) is wrong since 'center is not a variable but everything else to correct
if you need more help please join out discord server, it would be faster for you get help there

**Comment by unholypersona** [comment]
> Uh that changes the modal, the image you sent is the popout. example: ![image](https://user-images.githubusercontent.com/26217384/240648578-726d5c83-6a16-4042-ab8d-9c56957cb4c6.png)
> 
> var(center) is wrong since 'center is not a variable but everything else to correct if you need more help please join out discord server, it would be faster for you get help there

**Comment by unholypersona** [comment]
> Uh that changes the modal, the image you sent is the popout. example: ![image](https://user-images.githubusercontent.com/26217384/240648578-726d5c83-6a16-4042-ab8d-9c56957cb4c6.png)
> 
> var(center) is wrong since 'center is not a variable but everything else to correct if you need more help please join out discord server, it would be faster for you get help there

I'm sorry, but I seem to be confused by your phrasing can you tell me what you mean by "everything else to correct" and can you confirm if it's a bug or just a mistake on my end?

**Comment by NyxIsBad** [comment]
Leo is saying that changing the user modal background variable does result in correct behavior. You are looking for a change in the user popout behavior, and you need to change the user popout position / user popout size variables for that.
