### ISSUE TITLE
[Feature Request] Square Icons in the Style of Comfy

### ISSUE THREAD

**Issue by P529** [ClearVision/ClearVision-v6#137]
### Did You Search Other Suggestions?

- [X] I have checked if this feature request exists already

### Is your feature request related to a problem?

No, not related to a problem.
I jsut noticed, that on Dbeditor, you're able to adjust the radius of the status but not the icons themself.

### Screenshots and/or description of the feature request.

The ability to adjust the radius of the icons.

### Why does the theme need this?

To allow for even more customizability!

**Comment by NyxIsBad** [comment]
I think this is doable already using custom css and some other addon themes, but I'll have to confirm
