### ISSUE TITLE
Theme not applying to the members list in servers

### ISSUE THREAD

**Issue by Kimaul37** [ClearVision/ClearVision-v6#14]
**Describe the bug**
The theme is not applying on the members list in servers.

**To Reproduce**
Go to any server you have and see the bug on the right of the screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/28737149/85922444-94821100-b883-11ea-91d9-6205c78d8475.png)

**Desktop :**
Canary 62404 (1f237db)
BBD 0.3.4 (32e6212)
Host 0.0.266
Injector 0.4.1
Windows 10 64-Bit (10.0.20150)

**Comment by LeafyLuigi** [comment]
currently canary only - i've attempted to fix this but it might i can't seem to get this to be fixed in base v6 without needing a new import. 

while we don't fix anything that's currently canary only, this is sort of an exemption for the time being.

**Comment by Chew** [comment]
All I did was clone the repo, built it, uploaded the main.css, and changed the url in my theme css @ import url to the uploaded file and it works fine

**Comment by xcruxiex** [comment]
Fixed twice, this can be closed now ^^ lol
