### ISSUE TITLE
[Feature Request] Add more selector placeholders

### ISSUE THREAD

**Issue by KraXen72** [ClearVision/ClearVision-v6#149]
### Did You Search Other Suggestions?

- [X] I have checked if this feature request exists already

### Is your feature request related to a problem?

In my [theme](https://github.com/KraXen72/rosebox/tree/master/discord), i ['import' your selector placeholders](https://github.com/KraXen72/rosebox/tree/master/discord/lib), because they're pretty useful. I tried to preserve the license as best as I could, but please let me know if it's not sufficient.

I have also created a few more selectors that were not in your list, that were useful, and a few fixes. [see this file](https://github.com/KraXen72/rosebox/blob/master/discord/lib/_rbMappings.scss). 

Would you agree to merge these selectors into your big list? I am asking, because i understand if you don't want to maintain additional selectors your theme does not use. 

If you agree, let me know if i should create a pull request adding these selectors, or if you're going to do it (and possibly keep some order you use) or something else entirely.

Thanks a lot

### Screenshots and/or description of the feature request.

-

### Why does the theme need this?

It would be good if i wouldn't need to maintain additional selectors myself, if you already maintain a list for your theme. But it's not a big deal since there are only a few currently.

### Additional context

I saw that your original list was somehow auto-generated, but it appears you just now update it manually? Would you mind explaining what is the current status of that? Just out of curiosity. Thanks.

**Comment by Leozard** [comment]
Sorry for the late reply, you can submit a PR for the additional selectors and we'll look at it. You can also join our discord cause the team is more active there. 

> I saw that your original list was somehow auto-generated, but it appears you just now update it manually? Would you mind explaining what is the current status of that? Just out of curiosity. Thanks.

We don't create a placeholder for every class that discord app uses to try to keep the file size small as possible. Most classes without placeholders in the theme are used once so we're got lazy
