### ISSUE TITLE
[Bug Report] online indicators on profiles stay green even if theyre offline

### ISSUE THREAD

**Issue by notnightwolf** [ClearVision/ClearVision-v6#154]
### Did You Search Other Issues?

- [X] I have checked other issues

### Does This Bug Show On The Default Theme?

- [X] I have reproduced this on the default theme

### Describe The Bug

title says everything, without the theme its fine.

### Reproduction Steps

```bash
1.Was confused why everyone is online
2.Disabled the theme
3.Found out that its fine without the theme
...
```

**Comment by NyxIsBad** [comment]
This is a known bug that has to do with a plugin. it might be colorsighted, but I'm not sure. join the support server and ping me and i'll help you out more if you need it
