### ISSUE TITLE
[Bug Report] background and color's not working when you use Editor 

### ISSUE THREAD

**Issue by MCRMSnow** [ClearVision/ClearVision-v6#161]
### Did You Search Other Issues?

- [X] I have checked other issues

### Does This Bug Show On The Default Theme?

- [X] I have reproduced this on the default theme

### Describe The Bug

background and color's not working when you use Editor  

### Reproduction Steps

```bash
1.tried others and worked fine 
2.only this one 
3.
...
```

**Comment by NyxIsBad** [comment]
If you can join the discord server and ping Nyx (night.flower) with a screenshot for further details that would be great. Alternatively, can you provide a screenshot of what you mean here? I believe that you might have used an incorrect image link, but regardless background is working fine on the theme right now

**Comment by Auron-FFX** [comment]
this is happening since the latest update

**Comment by NyxIsBad** [comment]
this was patched a while ago, just forgot to close the issue. this was part of a much bigger break on discord
