### ISSUE TITLE
[Bug Report] Missing Optionsbutton

### ISSUE THREAD

**Issue by KarLitoDE** [ClearVision/ClearVision-v6#165]
### Did You Search Other Issues?

- [X] I have checked other issues

### Does This Bug Show On The Default Theme?

- [X] I have reproduced this on the default theme

### Describe The Bug

Hello,

while using the Plugin https://betterdiscord.app/plugin/GameActivityToggle the option button is missing. 
![image](https://github.com/ClearVision/ClearVision-v6/assets/147842374/a43145b3-92c1-4c65-8429-04916dd8965c)

Can you please update the theme for that - I can't go to discord settings anymore :D

### Reproduction Steps

```bash
1. Using Plugin https://betterdiscord.app/plugin/GameActivityToggle
2. Activate ClearVision Theme
```

### Screenshots

```bash
https://user-images.githubusercontent.com/147842374/274936772-a43145b3-92c1-4c65-8429-04916dd8965c.png
```

**Comment by NyxIsBad** [comment]
Can you join the support server and make a ticket there? This bug is known but should have been patched already, so you are likely running a different version of discord that I'd like details on.
