### ISSUE TITLE
[Bug Report] ClearVision doesn't work on the latest version of Discord

### ISSUE THREAD

**Issue by RhenaudTheLukark** [ClearVision/ClearVision-v6#167]
### Did You Search Other Issues?

- [X] I have checked other issues

### Does This Bug Show On The Default Theme?

- [X] I have reproduced this on the default theme

### Describe The Bug

When the theme's enabled, the backgrounds are back to Discord's main colors instead of the usual ClearVision background.

### Reproduction Steps

```bash
1. Download Discord's latest version.
2. Download BetterDiscord and ClearVision.
3. Enable ClearVision on the Themes tab, in the Options.
4. Discord's background should be visible instead of ClearVision's.
```

### Screenshots

```bash
https://i.imgur.com/6Z0QqaM.png
```

**Comment by Viper2kUK** [comment]
Should be bumped to a verified bug due to the issue of Discord's update as well as the issue with the css ( " -- " ) and background blur.  Remove the blur and the background loads in.

HTH
V2k.

**Comment by ivymothzz** [comment]
same problem here

**Comment by FailSafeNow** [comment]
Yup.

**Comment by NiK4o121** [comment]
Same here! Will you fix this bug?

**Comment by itinerare** [comment]
The BetterDiscord update seems to have resolved the issue!

**Comment by untuned** [comment]
BetterDiscord fixed the issue upstream

**Comment by Game4Fun-YT** [comment]
I have this issue on Vencord right now I am using it through online themes
