### ISSUE TITLE
[Bug Report] White box shows up when adding a role.

### ISSUE THREAD

**Issue by DTACat** [ClearVision/ClearVision-v6#168]
### Did You Search Other Issues?

- [X] I have checked other issues

### Does This Bug Show On The Default Theme?

- [X] I have reproduced this on the default theme

### Describe The Bug

When i want to add a role to a user it shows a white box so i cant see what roles im adding

### Reproduction Steps

```bash
1. Go to a server you own.
2. click on someones profile.
3. click the plus under the **ROLES** tab
```

### Screenshots

```bash
https://cdn.discordapp.com/attachments/1136130967128514613/1170150328805621780/image.png
```

**Comment by NyxIsBad** [comment]
should be patched
