### ISSUE TITLE
[Bug Report] Big spacing begtween name and date

### ISSUE THREAD

**Issue by haShinui** [ClearVision/ClearVision-v6#169]
### Did You Search Other Issues?

- [X] I have checked other issues

### Does This Bug Show On The Default Theme?

- [ ] I have reproduced this on the default theme

### Describe The Bug

So there is a wierd spacing between the name and the date it was written together with the message.
I here a screenshot of one message
It just happend today when I woke up and no idea what the problem could be, it just happens if I apply clear vision theme, no problem with other themes or default theme.
Also reinstalled it but didnt fix the problem,
( I can't paste screenshot in screenshot section)
![grafik](https://github.com/ClearVision/ClearVision-v6/assets/67230963/b7c7e68d-f5b0-4fcd-9dd4-8060eaebaaeb)

### Reproduction Steps

```bash
1. Install clear vision
2. I dont know what more.
...
```

**Comment by NyxIsBad** [comment]
Can you join the support server? This doesn't show up in the default theme and is likely caused by a plugin or custom css conflict, which I can more easily resolve in the support server. Regardless, I don't think this is a bug with the theme itself
