### ISSUE TITLE
[Bug Report] Glow around channel date markers when background blur is applied

### ISSUE THREAD

**Issue by Leah96xxx** [ClearVision/ClearVision-v6#181]
### Did You Search Other Issues?

- [X] I have checked other issues

### Does This Bug Show On The Default Theme?

- [X] I have reproduced this on the default theme

### Describe The Bug

When the variable `--background-blur` is set to anything other than 0px, there will be a glow around the date markers in channels. It is more pronounced with higher blur values.

The issue exists on both with both my customised theme and with the default theme (with blur applied of course), and have tried restarting Discord too.

### Reproduction Steps

1. Apply ClearVision theme
2. Set `--background-blur` to any value other than 0px and apply changes.

### Screenshots

Screenshot below is the default theme with the `--background-blur` variable set to 5px: 
![image](https://github.com/ClearVision/ClearVision-v6/assets/88419550/5b17b24c-b534-49df-9c0c-b5e2796440cb)

Same but with 10px:
![image](https://github.com/ClearVision/ClearVision-v6/assets/88419550/74ea721c-c6ca-44a7-8144-0dcab9539a46)

### Additional Context

ClearVision v6.3.0
BetterDiscord v1.9.7
Discord Stable 256231 (96a39c5)

**Comment by NyxIsBad** [comment]
Thanks for the bug report, and apologies for the late response. For a faster communication I suggest joining the discord server and pinging me because I check it way more often. 

The bug report can be replicated, and I'll try to find a fix for it.

**Comment by NyxIsBad** [comment]
should be fixed!

**Comment by Leah96xxx** [comment]
Confirmed it's fixed at my end. Thanks.
