### ISSUE TITLE
[Feature Request] Add style variable for grey-dot experiment.

### ISSUE THREAD

**Issue by Benji7010** [ClearVision/ClearVision-v6#188]
### Did You Search Other Suggestions?

- [X] I have checked if this feature request exists already

### Is your feature request related to a problem?

When using latest release of the theme, the grey dot from one of discord's latest experiments doesn't appear in the theme making channels with the grey dot not to appear with unread messages. 

### Screenshots and/or description of the feature request.

Adding back the dot to the theme or adding a style or variable will make the grey dot experiment visible.
![image](https://github.com/ClearVision/ClearVision-v6/assets/82925364/571da0c5-1dae-49b7-a04b-9e999ef4f8d1)
![image](https://github.com/ClearVision/ClearVision-v6/assets/82925364/9ce5e7d9-03a7-427c-9c12-aa7ec8204ac3)

### Why does the theme need this?

If the grey dot is added, then the theme will be out of date with app functionality.

### Additional context

Grey Dot is an experiment where it revises the notification system. It allows the changing of notification settings when turned on and adds a gray dot notification to guild chats. They don't ping the user or display a white dot on the guild when a new message appears in a chat or guild with mentions only.

**Comment by NyxIsBad** [comment]
If this is currently still an experiment then we're not going to theme it yet; most of the time experiments don't push to stable. If it does, we will fix it then. Thanks for the report though!
