### ISSUE TITLE
[Bug Report] Member width is not variable even though MemberList width is

### ISSUE THREAD

**Issue by Neshura87** [ClearVision/ClearVision-v6#191]
### Did You Search Other Issues?

- [X] I have checked other issues

### Does This Bug Show On The Default Theme?

- [X] I have reproduced this on the default theme

### Describe The Bug

When increasing the variable `members-width` the text in the members list still cuts off as if the list width had not been altered.

### Reproduction Steps

```bash
1. Have overflowing text in member list
2. Increase variable `members-width`
3. Overflowing text is still present
```

### Screenshots

Default:
![Screenshot_20240324_154356](https://github.com/ClearVision/ClearVision-v6/assets/48772737/0d8e66db-924e-4aaf-a633-c3297a6ddde9)

`members-width` set to 400px:
![Screenshot_20240324_154436](https://github.com/ClearVision/ClearVision-v6/assets/48772737/7597ca09-8b3a-4e57-a2cd-90c7928a4969)

### Additional Context

Adding the following to the custom CSS section helped me fix the problem but as I'm unfamiliar with discord css there might be unintended consequences I have not yet found:
```
.member_aa4760 {
    max-width: calc(var(--members-width) - 16px);
}
```

16px is the default difference between the width of the discord member list and the width of an individual member entry so I simply copied it over

**Comment by NyxIsBad** [comment]
I pushed a fix, reload your theme and check if it's fine. closing this issue, if you need more help join the discord server and ping me since I just don't check gh enough
