### ISSUE TITLE
Theme not working

### ISSUE THREAD

**Issue by Dragontechreal** [ClearVision/ClearVision-v6#192]
### Did You Search Other Issues?

- [X] I have checked other issues

### Does This Bug Show On The Default Theme?

- [X] I have reproduced this on the default theme

### Describe The Bug

Theme not working since last discord update

### Reproduction Steps

```bash
1.Disable and enabled theme
2.reinstalled theme
3.look at betterdiscord issues 
...
```

**Comment by Leozard** [comment]
if it's not fixed yet, can you join our server and open a support ticket?
