### ISSUE TITLE
[Bug Report] Issue Description Bad contrast for userspace buttons

### ISSUE THREAD

**Issue by Lolol4572** [ClearVision/ClearVision-v6#194]
### Did You Search Other Issues?

- [X] I have checked other issues

### Does This Bug Show On The Default Theme?

- [X] I have reproduced this on the default theme

### Describe The Bug

![Screenshot 2024-04-15 113916](https://github.com/ClearVision/ClearVision-v6/assets/87130878/9d24c63f-d034-46dc-8672-f2ada951bb93)

### Reproduction Steps

```bash
1.
2.
3.
...
```

**Comment by Leozard** [comment]
change the popout or text color?

**Comment by NyxIsBad** [comment]
join the discord and ping me if you want to communicate better; but check for light mode, and are you using a custom nitro discord profile?

**Comment by Lolol4572** [comment]
Yep, I am. Additionally, other themes don't seem to have this issue with custom nitro.

**Comment by Lolol4572** [comment]
The bottom text has terrible contrast, while the top doesn't. Additionally, this isn't an issue on any other themes from the BD repo.

**Comment by Lolol4572** [comment]
Text color.

**Comment by Leozard** [comment]
Discord nitro themes? If so we don't support them

**Comment by Lolol4572** [comment]
> change the popout or text color?

What parameter should change the color for those buttons?
