### ISSUE TITLE
[Bug Report] Graphic Glitches

### ISSUE THREAD

**Issue by Aholicknight** [ClearVision/ClearVision-v6#197]
### Did You Search Other Issues?

- [X] I have checked other issues

### Does This Bug Show On The Default Theme?

- [X] I have reproduced this on the default theme

### Describe The Bug

https://github.com/ClearVision/ClearVision-v6/assets/7843719/ae9e265c-1793-42dd-a6a4-67423f9f6bc3

For some reason, I am having graphical glitches when using the ClearVision theme. The only thing I changed was the background, and even when reverting, it still shows these graphical issues. I do not know what is causing this.

### Reproduction Steps

```bash
1. Turn on the ClearVision theme
2. Open images, move stuff fast, replicate what I did in the video
3. You will see graphical issues, such as text staying, and more.
...
```

### Screenshots

```bash
Video is attached
```

**Comment by Leozard** [comment]
try clearing ur cache or restarting or pc?

**Comment by megakarlach** [comment]
Also happen to me aswell, occasionally.

**Comment by BabyBoySnow** [comment]
> > try clearing ur cache or restarting or pc?
> 
> @Leozard how would I clear my cache?

Depending on your OS there is multiple ways to clear your cache, assuming you're using windows you can find your caches by following these steps.
First close discord fully, you can check that discord is fully closed by clicking the arrow on the bottom right of your taskbar.
Press the windows key and type `%appdata`, locate your discord folder, find every folder that has the word `cache` in it. Delete them.

**Comment by Aholicknight** [comment]
Closing this issue since I reinstalled windows a while ago and the problem went away.
