### ISSUE TITLE
[Bug Report] forced to have theme default, can't have discord default

### ISSUE THREAD

**Issue by Dominilk01** [ClearVision/ClearVision-v6#199]
### Did You Search Other Issues?

- [X] I have checked other issues

### Does This Bug Show On The Default Theme?

- [X] I have reproduced this on the default theme

### Describe The Bug

can't disable a feature

### Reproduction Steps

```bash
example:
1. replace --background-image with /*--background-image
2. if it not find a var it will put the default
```

### Additional Context

![Screenshot 2024-06-25 230757-2](https://github.com/ClearVision/ClearVision-v6/assets/108392199/1d4ffa14-b9d9-4a5a-93c7-b158ecc0cc96)

**Comment by Leozard** [comment]
That is intended. If u want a theme with the discord default background you try looking for other themes
