### ISSUE TITLE
[Bug Report] TabBar Broken

### ISSUE THREAD

**Issue by biogenik** [ClearVision/ClearVision-v6#203]
### Did You Search Other Issues?

- [X] I have checked other issues

### Does This Bug Show On The Default Theme?

- [X] I have reproduced this on the default theme

### Describe The Bug

Tab bar is default coloring and no theme applied to it. Broken on default theme as well as custom. I see it was moved to a different folder 2 weeks ago, but this issue only started today. 

![Discord_2024-07-12_14-46-17](https://github.com/user-attachments/assets/4f8253ba-9357-4d5e-b311-b477c9b2d7a6)

### Reproduction Steps

```bash
1. Open discord.
2. See broken tab bar :p
```

### Additional Context

Only tested using Vencord, unsure about other injection programs.

**Comment by deadHvman** [comment]
im seeing this aswell

**Comment by WasteFeIIow** [comment]
having this issue as well

**Comment by biogenik** [comment]
Fixed and working correctly, as mentioned in #204. Thanks.
