### ISSUE TITLE
[question] how to make less transparency/solid color?

### ISSUE THREAD

**Issue by Makezu90** [ClearVision/ClearVision-v6#211]
How i can make right click menu, when search and user popout solid color?

thank you! :)

![2](https://github.com/user-attachments/assets/d43f27d3-cfed-4bf3-81e9-c997a6c8610e)
![1](https://github.com/user-attachments/assets/64e7e919-f43f-45bd-a21f-4ed39a69b3d5)
![kuva](https://github.com/user-attachments/assets/f934721e-5b91-4efc-8776-06d2118b8ff6)

**Comment by untuned** [comment]
This question is better suited for the Discord server.
