### ISSUE TITLE
The channels part in servers is not working with last Canary update !

### ISSUE THREAD

**Issue by Kimaul37** [ClearVision/ClearVision-v6#22]
**Describe the bug**
In servers, the channels part is not supported by the theme after Discord Canary's last update yesterday.

**To Reproduce**
Just go in any server with the theme enabled.

**Screenshots**
![image](https://user-images.githubusercontent.com/28737149/98803267-c4861700-2414-11eb-868e-add1ebb2d344.png)

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/28737149/98803646-5f7ef100-2415-11eb-88c9-2d5c7a16e53f.png)

**Comment by zelyshia** [comment]
I am having a similar issue after the recent update.

**Comment by Pompanomike69** [comment]
I am also having this issue with the most recent stable build

**Comment by AnderssonMendietaRodriguez** [comment]
el aspect
![Captura de pantalla 2020-11-15 051005](https://user-images.githubusercontent.com/40446218/99182139-14a8f600-2701-11eb-8a5a-6214732adcf7.png)
o de los usuarios de voz esta normal, si se pudiera corregir ese error

**Comment by xcruxiex** [comment]
Fixed.
