### ISSUE TITLE
Compatibility Issue With TopRoleEverywhere

### ISSUE THREAD

**Issue by Ryonez** [ClearVision/ClearVision-v6#27]
**Describe the bug**
This them has an issue when displaying roles in the chat, such as when added by TopRoleEverywhere. It has a visual effect were a large amount of empty space is inserted from the left side of the role block through to the start of the text with the roles name. 

**To Reproduce**
1. Install Clearvision-v6
2. Install TopRoleEverywhere by DevilBro (I'm using v3.0.5)
3. Enable the plugin, defaults should suffice.
4. To to a server were users have colored roles applied to them.
5. See issues next to those users usernames.

**Screenshots**
Without theme:
![image](https://user-images.githubusercontent.com/16157130/104385422-14f62e00-5598-11eb-9cda-60322141e7d0.png)

With theme:
![image](https://user-images.githubusercontent.com/16157130/104385375-014ac780-5598-11eb-9753-8137e0c8f092.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 64-Bit (10.0.19042)
 - Discord version: Stable 74266 (98f1cc3)
 - Client/BBD Version: BBD 0.3.5

**Comment by iamilam** [comment]
Doesnt happen for me- well, it used to not happen to me but now that clearvision isnt working idk how to include a screenshot

**Comment by Ryonez** [comment]
I mean this is clearly an issue with the theme, would be nice to see some feedback outside of the issue just being waved off. Seem to work right when replies are used.

![image](https://user-images.githubusercontent.com/16157130/140818898-1e444896-e1d4-44b0-aa5b-d3882a80ec76.png)


Looks like to get it in line with tags, flex needs to be removed on this line:
https://github.com/ClearVision/ClearVision-v6/blob/bb17ceb9ba0b2732cb360c6a671bb2f4af0624a7/src/users/role.scss#L5

That'll get this, caused by an `display: inline-flex;` further up the chain:
![image](https://user-images.githubusercontent.com/16157130/140820805-4bb8dfdb-5ac5-437a-a4c7-0cab15e987c4.png)


As you can see though, the tag still looks out of place. After some poking around, I've found adding this as a custom css in Bandage Discord alleviates that problem.
```
.tag-wWVHyf {
    height: .9375rem;
    padding: 0 .275rem;
    margin-top: .075em;
    margin-left: .25rem;
    vertical-align: top;
    border-radius: .1875rem;
    top: .15rem;
    position: relative;
}
```
This brings it in line with the bot tags:
![image](https://user-images.githubusercontent.com/16157130/140824096-6a62a622-f4a3-492d-8dd8-eb3002621cb6.png)


I'm hoping this will be looked at again, but even if it isn't, I hope this information helps others who find this bug.
