### ISSUE TITLE
Custom CSS doesn't work

### ISSUE THREAD

**Issue by krishaayjois21** [ClearVision/ClearVision-v6#41]
**Describe the bug**
So basically , I made a copy of your default [main.css](https://clearvision.gitlab.io/v6/main.css) and edited the css file to import that so I can change the default main.css. But it doesnt seem to apply the theme when I use my copy even if it is an exact copy of your default css. IT only works when importing the one from gitlab

**To Reproduce**
1. Go to 'Settings > Themes > ClearVision'
2. Click on 'Edit'
3. Scroll down to 'Line 14'
4. Change URL to new CSS

**Screenshots**
![image](https://user-images.githubusercontent.com/62088268/117602765-1d89fa00-b16f-11eb-865d-458117995a46.png)
- Same Default main.css hosted on somewhere else , no theme styling
![image](https://user-images.githubusercontent.com/62088268/117602865-5033f280-b16f-11eb-9f70-5d416e2d1919.png)
- Default main.css but from clearvision's gitlab , themes are applied

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Discord version: Stable 84336 (eeeadc8)
 - Client/BBD Version: BetterDiscord 1.1.0

**Additional context**

**Comment by krishaayjois21** [comment]
Also a workaround for this is manually copying each style from the main.css to the theme css in the themes folder and making required edits

**Comment by Leozard** [comment]
you need to enable github pages and use that link from there to be able to import files. plus u can just make any additional customisations by putting the code inside your theme file

**Comment by krishaayjois21** [comment]
Ah I see. Thank You
