### ISSUE TITLE
New reaction marks not claiming color

### ISSUE THREAD

**Issue by Thedoczek** [ClearVision/ClearVision-v6#43]
**Describe the bug**
Discord introduced new reaction marks. They don't claim the color of style (green in my case).

**Screenshots**
![obraz](https://user-images.githubusercontent.com/69758777/117816157-82744b80-b266-11eb-8525-cb1a33d0f081.png)

**Desktop**
 - OS: Windows 10 64-Bit (10.0.19042)
 - Discord version: Stable 84451 (5a9f566)
 - Client/BBD Version: BD 1.0.0 (stable)

**Comment by Leozard** [comment]
should be fixed

**Comment by Thedoczek** [comment]
Should come back to old :/

**Comment by Leozard** [comment]
old how?
it's already same before rebrand

**Comment by Thedoczek** [comment]
![obraz](https://user-images.githubusercontent.com/69758777/118769691-bbbd4480-b880-11eb-907c-792da595559a.png)
This one

**Comment by Thedoczek** [comment]
![obraz](https://user-images.githubusercontent.com/69758777/118769805-d98aa980-b880-11eb-950a-76a51e49b6bd.png)
ACtually I discovered it works with RevertRebrand theme
![obraz](https://user-images.githubusercontent.com/69758777/118769882-ed361000-b880-11eb-96b8-636e0e61c2b8.png)
