### ISSUE TITLE
The @ menu doesn't have theme applied

### ISSUE THREAD

**Issue by StarrKiss** [ClearVision/ClearVision-v6#44]
So this is what my settings look like with this theme:
![image](https://user-images.githubusercontent.com/13007697/118318717-628b9480-b4bf-11eb-85f0-2c618417a12a.png)

this works throughout most of the UI, except in the @ menu, where it's just black and semitransparent. NONE of the options in the CSS same to change the color of this.

![image](https://user-images.githubusercontent.com/13007697/118318805-7e8f3600-b4bf-11eb-9cd7-bb721ee6fb94.png)

This is completely different to the aesthetic of the rest of the UI.
Here are my theme settings (as TXT since Github doesn't support uploading css files):
[ClearVision_v6.theme.txt](https://github.com/ClearVision/ClearVision-v6/files/6480796/ClearVision_v6.theme.txt)

**Desktop (please complete the following information):**
 - OS: Linux
 - Discord version: Autolatest
 - Client/BBD Version: Autolatest

**Comment by StarrKiss** [comment]
This actually applies to a bunch of different modals, such as the 
![image](https://user-images.githubusercontent.com/13007697/118319035-d3cb4780-b4bf-11eb-80fa-e1797a70128c.png) popupmenu, DESPITE me properly setting modals in config

**Comment by Leozard** [comment]
there's not config to change those atm. unless you're referring to --user-modal-image which only changes this part
![image](https://user-images.githubusercontent.com/26217384/118596578-236e8380-b7de-11eb-9935-a7c27ae4372b.png)
