### ISSUE TITLE
--font-size

### ISSUE THREAD

**Issue by firereverie** [ClearVision/ClearVision-v6#45]
Please?

**Comment by firereverie** [comment]
```
html {
    font-size: var(--font-size) !important;
}
```
Added this to my custom CSS (which does work? for me anyways) as a workaround, and a --font-size line to the theme config.

**Comment by Leozard** [comment]
discord already has an inbuilt chat font slider in user settings -> appearance. it would be hard to add this as different areas uses different font sizes

**Comment by untuned** [comment]
This is already a feature in Discord as said above, will be closing this.
