### ISSUE TITLE
Theme doesn't apply in stage discovery tab

### ISSUE THREAD

**Issue by Veysinator** [ClearVision/ClearVision-v6#48]
**Describe the bug**
In the newest update of discord, stage discorvery feature was added. But Clear Vision theme isn't adapted to the css yet. It would be great if you can implement theme into the stage discovery tab.

**To Reproduce**
1. Install 'Clear Vision'
2. Open 'Discord'
3. Click on 'Stage Discovery'
4. See default theme

**Screenshots**
![resim](https://user-images.githubusercontent.com/71281955/119649574-74f4bf00-be2b-11eb-9755-df38dee9b4ad.png)
![resim](https://user-images.githubusercontent.com/71281955/119650270-4aefcc80-be2c-11eb-9529-4e637c2ecda5.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Discord version: [Canary 86052 (8878c54)]
 - Client/BBD Version: [BetterDiscord 1.1.1]

**Comment by Leozard** [comment]
I'll look into it asap

**Comment by Leozard** [comment]
fixed
