### ISSUE TITLE
ClearVision version covers Home Button.

### ISSUE THREAD

**Issue by BreezeGH** [ClearVision/ClearVision-v6#49]
**Describe the bug**
The "CV {versionnumber}" display covers the Home Button, not allowing me to click on it without pressing the very bottom of the home button, which is relatively uncomfortable.

**To Reproduce**
- No steps, CV automatically covered screen.

**Screenshots**
![Screen Shot 2021-05-26 at 1 42 29 PM](https://user-images.githubusercontent.com/77531000/119706752-5e993400-be28-11eb-9f49-df9021549178.png)

**Desktop (please complete the following information):**
 - OS: macOS High Sierra 10.13.6 (OS X 10.13.6 (17.7.0))
 - Discord version: Canary 86068 (48dc74f)
 - Client/BBD Version: Powercord v2 (b2dda82)

**Additional context**

**Comment by Leozard** [comment]
as far as I'm aware no where in the base theme has the word "CV" in it

**Comment by Leozard** [comment]
nvm it's there but I don't have a mac so it might take a while

**Comment by Leozard** [comment]
had someone with a mac to test it and it's an issue with your server columns
