### ISSUE TITLE
Syntax type in the corner

### ISSUE THREAD

**Issue by Thedoczek** [ClearVision/ClearVision-v6#56]
Hi! How did you do that
![obraz](https://user-images.githubusercontent.com/69758777/122985255-3efd1900-d39e-11eb-9ecc-3e35faee64ad.png)
and that?
![obraz](https://user-images.githubusercontent.com/69758777/122985281-46242700-d39e-11eb-8f87-b44a127050e2.png)

Can I use it?

**Comment by Leozard** [comment]
it's in https://github.com/ClearVision/ClearVision-v6/blob/master/src/messages/codeLanguages.scss
or you can look in the main.css here https://clearvision.gitlab.io/v6/main.css#:~:text=/*%20CODEBLOCK%20LANGUAGES%20*/

**Comment by Thedoczek** [comment]
Thanks!

pt., 25 cze 2021, 05:30 użytkownik Leozard ***@***.***>
napisał:
