### ISSUE TITLE
New User Profile screws up settings screen/profile on ClearVision

### ISSUE THREAD

**Issue by Drflash55** [ClearVision/ClearVision-v6#57]
**Describe the bug**
Due to the new update where people can set "About Me" and their Profile Banner, this messes up the placement of your profile icon (and name/badge icons). PFP icon on their profile doesn't match up with how Discord handles it either.

**To Reproduce**
Go into the settings, and the profile icon will be in the wrong spot.
Same thing when you click on your name to view their profile (PFP doesn't have anything covering up behind it).

**Screenshots**
![image](https://user-images.githubusercontent.com/13694448/123351530-430a7180-d52b-11eb-9285-3939fdd1ec42.png)
![image](https://user-images.githubusercontent.com/13694448/123351392-00e13000-d52b-11eb-8dc7-6c2b10fcb9fc.png)

This is what it's supposed to look like without the theme.

![image](https://user-images.githubusercontent.com/13694448/123351493-3128ce80-d52b-11eb-8a85-ad67151b0987.png)
![image](https://user-images.githubusercontent.com/13694448/123351451-1b1b0e00-d52b-11eb-8413-ba47aef06e41.png)

**Desktop:**
 - OS: Windows 10 Home 64-Bit (10.0.19042)
 - Discord version: Stable 88738 (b63dc2c)
 - Client/BBD Version: BetterDiscord 1.1.1

**Additional context**
This might be easily fixable by just fixing up some of the coding in the style, but I don't know how CSS's work.

**Comment by WhatsWhatMC** [comment]
I also have a similar issue.
This is what I see when I click on my friend's name.
![6c1fc8a16b13c2378ede2da4046ceae4](https://user-images.githubusercontent.com/30912203/123361322-d7c99b00-d53c-11eb-8889-21c5b62cd327.jpg) 
This is what I see when I click on my name. 
![e8d61f478136851bdbcaf70d6c0aaddf](https://user-images.githubusercontent.com/30912203/123361328-db5d2200-d53c-11eb-9a9c-bc4f0f2ffa2a.jpg)

OS: Windows 10 Pro 64-Bit (19042.1052)
Discord version: Stable 88738 (b63dc2c)
Client/BBD Version: BetterDiscord v1.1.1

**Comment by Leozard** [comment]
fix is coming soon
