### ISSUE TITLE
Certain screens don't work when using discord light mode

### ISSUE THREAD

**Issue by RipYoda** [ClearVision/ClearVision-v6#60]
**Describe the bug**
Certain screens such as the friends menu don't work with the theme

**To Reproduce**
1. Go to settings
2. Click on appearance
3. Hit light mode
4. You'll see it

**Screenshots**
With Light Mode:
![image](https://user-images.githubusercontent.com/86500663/123493841-68f34d00-d5e3-11eb-83a8-5e31428556d4.png)
With Dark Mode:
![image](https://user-images.githubusercontent.com/86500663/123494397-4c581480-d5e5-11eb-8427-6a0904f68259.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (20H2)
 - Discord version: Stable 88806 (ec5c1a3)
 - Client/BBD Version: Better Discord 1.1.1

**Additional context**

**Comment by Leozard** [comment]
support for light mode was dropped few years ago
