### ISSUE TITLE
Different Buttons have the same color

### ISSUE THREAD

**Issue by SteffoSpieler** [ClearVision/ClearVision-v6#68]
**Describe the bug**
Message-Buttons have the same color, even though they are different types.

**To Reproduce**
1. Create a Message with Buttons with a Bot
2. See bad css

**Screenshots**
|With ClearVision|Without ClearVision|
|-----------------|--------------------|
|![grafik](https://user-images.githubusercontent.com/41108856/133308713-a9dfd447-b048-4184-9dfe-0a7271e3586b.png)|![grafik](https://user-images.githubusercontent.com/41108856/133308825-f6055a26-3bac-4238-8a1c-566057cd7b81.png)|

**Desktop (please complete the following information):**
 - OS: Windows
 - Discord version: Stable 97097 (0ca818c)
 - Client/BBD Version: BetterDiscord 1.2.1

**Comment by Leozard** [comment]
it's supposed to that, most buttons are changed to match your main color
