### ISSUE TITLE
Scroll bar in settings

### ISSUE THREAD

**Issue by Har27Coder** [ClearVision/ClearVision-v6#70]
I am not able to scroll in the settings of discord when using this theme.

I wanted to enable some new plugins I just installed but there was no scroll bar in the settings menu on the left and all betterdiscord options are almost at the bottom of the menu.

**Comment by Leozard** [comment]
https://support.microsoft.com/en-us/windows/touch-gestures-for-windows-a9d28305-4818-a5df-4e2b-e5590f850741
