### ISSUE TITLE
Server columns

### ISSUE THREAD

**Issue by big-mak** [ClearVision/ClearVision-v6#71]
When using folders with multiple server columns, opening folders causes other folders to move, creating large gaps.
![Screenshot 2021-10-26 at 16 39 09](https://user-images.githubusercontent.com/82375998/138913241-5caedd03-d0d4-4245-b0eb-f82c6d94b000.png)
Making the columns completely independent of each other would allow for much more efficient use of space.

**Comment by NyxIsBad** [comment]
Server columns has been discontinued as a theme functionality for a significant portion of time. The plugin is not supported.

Closing issue because it's irrelevant - consider opening an issue with the relevant plugin, or if you are using an old version of the theme, updating.
