### ISSUE TITLE
Transparency inconsistency, overlooked?

### ISSUE THREAD

**Issue by Limerance** [ClearVision/ClearVision-v6#72]
_**Is your feature request related to a problem? Please describe.**_
Hello, I think there's an overlook of transparency options here.
https://i.itsukarine.art/erbtV.png
![image](https://user-images.githubusercontent.com/3655365/141432444-bce7533d-5092-4a8b-b2a4-74fec1107d53.png)
The text input bar is doing it's own thing when it comes to transparency, and when you set the entire background-shading to 0, the bar basically the only thing really really sticking out with far more opacity than any other element.

_**Describe the solution you'd like**_
I pulled the theme editor out for your theme and grabbed the area's css with console, it seems to be
```
.channelTextArea-2VhZ6z {
  background: rgba(0, 0, 0, 0.6);
``` 
by default.

I think the best solution would be to implement an option for it in your root settings that come with the theme, so users less savvy who wish to recreate a more "consistently" smooth background-shading experience can do so like I did, it does seem like all the other slightly-off elements are set to 0.3, and it matches when adjusted to that.
If the other slightly-different opacity elements can be considered, you could maybe combine all of these together into a single option in root. I however am not savvy enough to know if that's actually doable.

_**Describe alternatives you've considered**_
I manually adjusted it in BetterDisc's custom css section and saw the results I wanted with the rgba alpha adjustment.

_**Additional context**_
Thank for you considering!

**Comment by Leozard** [comment]
It's a design choice to ensure it is always visible. For non-tech savvy user they can join and ask in our discord server. I appreciate your suggestion but so far you are the only one that wants that feature so it won't be considered anytime soon
