### ISSUE TITLE
Clear Vision broken after PC restart

### ISSUE THREAD

**Issue by niicholai** [ClearVision/ClearVision-v6#74]
**Describe the bug**
ClearVision suddenly stopped loading or something.  When using ClearVision after restarting my computer nothing happens.  The other three themes I have if I turn them on it works fine, but now ClearVision does nothing.  However if I turn on DarkMatter and then ClearVision it kind of half ass shows up together.

**To Reproduce**
- Restart computer
- Open up discord all BD plugins run except the theme
- Turn CV on and off nothing happens
- Turn on DarkMatter theme works fine
- Turn on CV after DM theme becomes a wonky mix of the two
- Turn DM back off and CV disappears too but is still on

**Screenshots**
- https://imgur.com/I4DC4C9 Themes showing CV on with no change
- https://imgur.com/UODaHby Themes showing another theme works
- https://imgur.com/a7G9Vaa A server showing what happens when DM is turned on first and then CV

**Desktop (please complete the following information):**
 - OS: Windows 10 64-Bit (10.0.19043)
 - Discord version: Canary 110259 (6ee542a)
 - Client/BBD Version: BetterDiscord 1.3.0

**Additional context**

**Comment by JoshMainstone** [comment]
I am having a similar issue where CV also doesn't come on properly even when it shows as on but other themes work.

**Comment by Johannes11833** [comment]
Got the same issue.

**Comment by LucyGears** [comment]
Same issue here. I really enjoy this theme, hopefully a fix will be forked soon.

**Comment by KurtArc** [comment]
Got the same issue here.

**Comment by asen23** [comment]
![image](https://user-images.githubusercontent.com/31660481/148862776-cf1ff6b3-4e83-406a-aef1-4925f7b2f71b.png)
Discord pushed an update that broke some theme/plugin, hope the author can fix it soon

**Comment by niicholai** [comment]
Theme seems to work for the most part, but doesn't work in the settings section any more now.
