### ISSUE TITLE
Discord Class Reroll

### ISSUE THREAD

**Issue by iHemoX3** [ClearVision/ClearVision-v6#75]
Tried repairing better discord, and it still didn't fix anything

![image](https://user-images.githubusercontent.com/92804812/148919951-831519cf-ea87-4dcc-9959-c1078046994b.png)

![image](https://user-images.githubusercontent.com/92804812/148919334-3ade7d0a-94bc-4d2f-bdd7-bb35bb003a70.png)

blacked out text is for my friends privacy, and some statuses have advertisements on them which I don't think would be appropriate here

**Comment by Nerwy** [comment]
Same issue since the last update on Canary, they probably changed some structural elements breaking a lot of CSS :x

**Comment by iHemoX3** [comment]
> 
 
im not even using canary lol, just normal discord

**Comment by lukakone** [comment]
> 

yep same issue for me...

**Comment by DoBsTeRa-100** [comment]
Just Build it from the source code with Node js. It worked for me

**Comment by iHemoX3** [comment]
> Just Build it from the source code with Node js. It worked for me

how?

**Comment by ThunderSHo** [comment]
Same issue

**Comment by thebluedev** [comment]
Can confirm, I have the same issue.

**Comment by ThunderSHo** [comment]
![Uploading Discord 11-01-2022 17_16_26.png…]()

**Comment by ThunderSHo** [comment]
![Discord 11-01-2022 17_16_26](https://user-images.githubusercontent.com/97519411/148938448-00088514-f7c9-4837-b1ba-67159da60d73.png)

**Comment by rachelwon96** [comment]
facing the same issue as well

**Comment by marto05** [comment]
I have the same issue.

**Comment by aquapi** [comment]
Same issue

**Comment by ThunderSHo** [comment]
How long does these types of issue take to be solved

**Comment by Dschogo** [comment]
Writting 10 times "same" doenst help, just spams. Instead react on the initial comment with a +1 or whatever. These issues occur because Discord updated whole lot in the last update which changed the css selectors, therefore the custom (skin) css cant overwrite the original one and has to be rewritten. 
Im not a contributor of this project but i guess it will take a bit (was just 3 days or so last time). Be patient. On the code or commit page you kinda can track the progress.
As seen in the commits, the devs already working on it with high effort, give them some time, dont forget they code such in free time.

**Comment by iamambrosian** [comment]
<img width="902" alt="image" src="https://user-images.githubusercontent.com/97527026/148951886-690015ac-0855-46e2-9d63-33d944f151fb.png">

I am also having these issues.

**Comment by einnicernutzer** [comment]
Yeah, i got the same issue since i logged on today :( 
I think it has to do with a new discord update in which they change something with the font / background feature because every BetterDiscord theme i have, has the same problem...

**Comment by iHemoX3** [comment]
Guys please, as Dschogo said, saying "same i had the same issue" doesn't help at all, it's just a useless notification, so unless you have something you can help me or everyone with, kindly, stay quite.

**Comment by untuned** [comment]
This is a known issue, Discord recently rerolled all of their class names, so theme and plugin developers need to go through and change all of them.

**Comment by Aholicknight** [comment]
rip all betterdiscord themes

**Comment by BlueStarBRS** [comment]
same problem here

**Comment by BlueStarBRS** [comment]
@Mentalscars  why closed?

**Comment by ThunderSHo** [comment]
> @Mentalscars why closed?

It's working now

**Comment by ThunderSHo** [comment]
Just reload it

**Comment by BlueStarBRS** [comment]
and this 2 have no icon but the other stuff is good like before 👍🏻

**Comment by BlueStarBRS** [comment]
![image](https://user-images.githubusercontent.com/25110093/149179526-8f4187f8-1925-4543-b3e9-38957c566a16.png)
and this 2 have no icon but the other stuff is good like before 👍🏻
