### ISSUE TITLE
theme not working with search bar in friends menu

### ISSUE THREAD

**Issue by iHemoX3** [ClearVision/ClearVision-v6#79]
The search bar in the friends menu in the version 6.2 is not loading

![image](https://user-images.githubusercontent.com/92804812/149217928-bbea3795-78c2-47b8-af8f-58cfacd1c673.png)

*only opening this ticket because it's infuriating*

**Comment by Zacam** [comment]
Theme is now applying to Search Bar (in or out of Friends):
![cv-FriendSearch](https://user-images.githubusercontent.com/2995385/149337993-14e83f39-4295-4249-b575-51f42e5dedc4.png)

However, channel Search popup is not themed the same as Pinned or Inbox is; uncertain if that should be a separate issue though.

**Comment by Zacam** [comment]
As of version 6.2.1, Sidebar "Search" pop-out is now themed.
