### ISSUE TITLE
Theme Stopped Working

### ISSUE THREAD

**Issue by Grip555** [ClearVision/ClearVision-v6#8]
Can we please get an updated version, with links that work?

**Comment by SteffoSpieler** [comment]
I don't know why, but the GitLab Page was deleted. (Or anything else with an Error 404) So your Discord can't load the css file from the gitlab page, because it was deleted.

**Comment by AhaoAile** [comment]
I have the same problem.

**Comment by Tename** [comment]
Its fixed

**Comment by pepek1122583** [comment]
And again :D Welcome to server down

**Comment by SwiftSmoothvZ** [comment]
hello its not working anymore
