### ISSUE TITLE
[Feature Request] camera and screenshare buttons not highlighting if active

### ISSUE THREAD

**Issue by 20Alexanderxx** [ClearVision/ClearVision-v6#85]
### Did You Search Other Suggestions?

- [X] I have checked if this feature request exists already

### Is your feature request related to a problem?

its good to see, if your camera is used in discord, if you are in a call but not in the voice-chat window to see, if your camera and/or screen share are still active

### Screenshots and/or description of the feature request.

i guess same as above

### Why does the theme need this?

native discord has it, so it would be great if this theme does it as well

**Comment by Leozard** [comment]
planned to be fixed soon, thx for your reminder tho :]
