### ISSUE TITLE
[Bug Report] User popup modal is misplaced.

### ISSUE THREAD

**Issue by seriaati** [ClearVision/ClearVision-v6#87]
### Did You Search Other Issues?

- [X] I have checked other issues

### Describe The Bug

The user popup modal is displaced as the screenshot shows.

### Reproduction Steps

```bash
1. Click on any user in the member list of a server.
```

### Screenshots

https://user-images.githubusercontent.com/61446626/154584151-dbc41687-14e1-4d2e-a2a7-b4ea5dcf855e.png

How it should look like: https://user-images.githubusercontent.com/61446626/154584519-3f2af700-8823-462e-bd38-579bdfab9882.png

**Comment by NyxIsBad** [comment]
This is a known bug. However, it's not fixable.

Cause of bug is actually because of an issue with electron and blurring. If you don't want this to ever happen, you could set user popout blur to 0, but either way can't be resolved by us
