### ISSUE TITLE
[Bug Report] Codeblock width in embed description is smaller than what its supposed to be

### ISSUE THREAD

**Issue by Endy3032** [ClearVision/ClearVision-v6#90]
### Did You Search Other Issues?

- [X] I have checked other issues

### Does This Bug Show On The Default Theme?

- [X] I have reproduced this on the default theme

### Describe The Bug

I was trying to make a wordle layout with a codeblock inside an embed description. The embed cut short and the keyboard letters were put onto a new line while without ClearVision enabled it fits perfectly.

### Reproduction Steps

```bash
1. Make a codeblock that has several separate lines of text
2. Put the codeblock in an embed's description
3. Send the message
4. Toggle CV off and see the lines fit perfectly, toggle CV on and see the lines get cut off into a new line
```

### Screenshots

```bash
See additional context since I cant paste screenshots here (maybe turn off bash render mode so its easier for people to paste and upload screenshots directly)
```

### Additional Context

ClearVision on
![image](https://user-images.githubusercontent.com/61771609/156875913-5f7fc694-491f-4aeb-a076-f41e71981220.png)
![image](https://user-images.githubusercontent.com/61771609/156875930-483d8328-84dd-4058-8a38-a173d19f239f.png)

ClearVision off
![image](https://user-images.githubusercontent.com/61771609/156875942-ec43c70d-0eba-4e81-ba39-e0673f677805.png)
![image](https://user-images.githubusercontent.com/61771609/156875944-75e4cc0d-a529-49f6-a380-cf678bef0c22.png)

**Comment by LeafyLuigi** [comment]
I no longer help maintain this theme but I feel this would be in the best interest of everyone who does - Can you please copy/paste the `raw` codeblock you are trying to send on Discord

**Comment by Endy3032** [comment]
> I no longer help maintain this theme but I feel this would be in the best interest of everyone who does - Can you please copy/paste the `raw` codeblock you are trying to send on Discord

What do you mean by that exactly? If you mean the raw embed then here they are.

Wordle board
```ansi
[0;40;37m   [0m [0;40;37m   [0m [0;40;37m   [0m [0;40;37m   [0m [0;40;37m   [0m
[0;40;37m   [0m [0;40;37m   [0m [0;40;37m   [0m [0;40;37m   [0m [0;40;37m   [0m
[0;40;37m   [0m [0;40;37m   [0m [0;40;37m   [0m [0;40;37m   [0m [0;40;37m   [0m
[0;40;37m   [0m [0;40;37m   [0m [0;40;37m   [0m [0;40;37m   [0m [0;40;37m   [0m
[0;40;37m   [0m [0;40;37m   [0m [0;40;37m   [0m [0;40;37m   [0m [0;40;37m   [0m
[0;40;37m   [0m [0;40;37m   [0m [0;40;37m   [0m [0;40;37m   [0m [0;40;37m   [0m

[0;40;37mQ[0m [0;40;37mW[0m [0;40;37mE[0m [0;40;37mR[0m [0;40;37mT[0m [0;40;37mY[0m [0;40;37mU[0m [0;40;37mI[0m [0;40;37mO[0m [0;40;37mP[0m
 [0;40;37mA[0m [0;40;37mS[0m [0;40;37mD[0m [0;40;37mF[0m [0;40;37mG[0m [0;40;37mH[0m [0;40;37mJ[0m [0;40;37mK[0m [0;40;37mL[0m
   [0;40;37mZ[0m [0;40;37mX[0m [0;40;37mC[0m [0;40;37mV[0m [0;40;37mB[0m [0;40;37mN[0m [0;40;37mM[0m
```
or with \u escape code
```ansi
\u001b[0;40;37m   \u001b[0m \u001b[0;40;37m   \u001b[0m \u001b[0;40;37m   \u001b[0m \u001b[0;40;37m   \u001b[0m \u001b[0;40;37m   \u001b[0m
\u001b[0;40;37m   \u001b[0m \u001b[0;40;37m   \u001b[0m \u001b[0;40;37m   \u001b[0m \u001b[0;40;37m   \u001b[0m \u001b[0;40;37m   \u001b[0m
\u001b[0;40;37m   \u001b[0m \u001b[0;40;37m   \u001b[0m \u001b[0;40;37m   \u001b[0m \u001b[0;40;37m   \u001b[0m \u001b[0;40;37m   \u001b[0m
\u001b[0;40;37m   \u001b[0m \u001b[0;40;37m   \u001b[0m \u001b[0;40;37m   \u001b[0m \u001b[0;40;37m   \u001b[0m \u001b[0;40;37m   \u001b[0m
\u001b[0;40;37m   \u001b[0m \u001b[0;40;37m   \u001b[0m \u001b[0;40;37m   \u001b[0m \u001b[0;40;37m   \u001b[0m \u001b[0;40;37m   \u001b[0m
\u001b[0;40;37m   \u001b[0m \u001b[0;40;37m   \u001b[0m \u001b[0;40;37m   \u001b[0m \u001b[0;40;37m   \u001b[0m \u001b[0;40;37m   \u001b[0m

\u001b[0;40;37mQ\u001b[0m \u001b[0;40;37mW\u001b[0m \u001b[0;40;37mE\u001b[0m \u001b[0;40;37mR\u001b[0m \u001b[0;40;37mT\u001b[0m \u001b[0;40;37mY\u001b[0m \u001b[0;40;37mU\u001b[0m \u001b[0;40;37mI\u001b[0m \u001b[0;40;37mO\u001b[0m \u001b[0;40;37mP\u001b[0m
 \u001b[0;40;37mA\u001b[0m \u001b[0;40;37mS\u001b[0m \u001b[0;40;37mD\u001b[0m \u001b[0;40;37mF\u001b[0m \u001b[0;40;37mG\u001b[0m \u001b[0;40;37mH\u001b[0m \u001b[0;40;37mJ\u001b[0m \u001b[0;40;37mK\u001b[0m \u001b[0;40;37mL\u001b[0m
   \u001b[0;40;37mZ\u001b[0m \u001b[0;40;37mX\u001b[0m \u001b[0;40;37mC\u001b[0m \u001b[0;40;37mV\u001b[0m \u001b[0;40;37mB\u001b[0m \u001b[0;40;37mN\u001b[0m \u001b[0;40;37mM\u001b[0m
```
Jumble of text (I deleted the embed with the jumble of text so this is the best i can get back from ocr)
```
alakissdklaidsilakdsiklakldaislidkaskljads
dasjkldsakildsakljljkdaslkjadsilkadskljads
jdwoadikljdksalsadiklldsaikiklsadsadikllkj
adsj1kkkkkkkkkkjaslkdj akljdklasjdkljasldj
```
also note that it only happens in embeds and not on a message since its width doesnt depend on the content
![image](https://user-images.githubusercontent.com/61771609/156921357-abedc5c7-e968-4712-9251-434bf098c379.png)

**Comment by NyxIsBad** [comment]
I'll look into it

**Comment by NyxIsBad** [comment]
Okay I forgot to reply to this thread, sorry about that (its been over a month)
I looked into the code at the time and couldn't identify which margin was causing the issue (which I'd assume is almost certainly the case)
It'd be nice if I could see the effect in discord somehow, but I feel bad asking for such a use of your time. If I can attempt to get a difference off of some other bot's embed (just comparing vanilla to clearvision) then I'll try to look more that way. Thanks for your bug report, and sorry that I'm so horridly inactive. 

If one of the other devs wants to take this issue on, feel free to, as I have excuses galore. In the meantime, I will try to get a bot to send me embeds lol

**Comment by Endy3032** [comment]
After a big of digging, I think I have found the cause of the problem
The `pre` element with the selector `.markup-eYLPri pre` in the style has `max-width` of only 93% causing the codeblock to not be the true width (notice the clipping & the right margin is a bit wide)
![Screen Shot 2022-04-28 at 6 45 55 PM](https://user-images.githubusercontent.com/61771609/165745087-2af9f4ca-acea-48cf-8497-50698ef8c666.png)
After changing its `max-width` to 100%, it's able to display properly again
![Screen Shot 2022-04-28 at 6 45 45 PM](https://user-images.githubusercontent.com/61771609/165745066-1ca10abd-8ac1-499f-80a8-681620149fb5.png)
ill make a pr for this rn
