### ISSUE TITLE
Flip background image vertically/horizontally

### ISSUE THREAD

**Issue by reynoldyehezkiel** [ClearVision/ClearVision-v6#95]
Is there any how to flip background image only?

**Comment by mxr2004** [comment]
Hi @reynoldyehezkiel, there is no way to apply a transformation to a background in CSS. The easiest thing would be to edit the background like you want it to be and load it in manually.

Use the theme editor referenced in the readme file or paste the base64 string into your CSS file as described in this Issue #94

**Comment by reynoldyehezkiel** [comment]
ok thanks

**Comment by Leozard** [comment]
flip vertically:
`.bg-1QIAus {
	transform: scaleY(-1);
}`

flip horizontally:
`.bg-1QIAus {
	transform: scaleX(-1);
}`

Paste these either in customCSS or at the bottom of the .css file.
Next time please ask in the discord server as we're most active there.
