### ISSUE TITLE
[Bug Report] Issue Description

### ISSUE THREAD

**Issue by Amail247** [ClearVision/ClearVision-v6#97]
### Did You Search Other Issues?

- [X] I have checked other issues

### Does This Bug Show On The Default Theme?

- [X] I have reproduced this on the default theme

### Describe The Bug

when I try to open settings, it won't load(I try to click and it refuses to open anything), I can't change the background, or remove it. I deleted it, and it still isn't gone. Can you please fix/change this? Because of this, all my settings doesn't work at all. Sorry if this comment in inconvinient and just on my side

### Reproduction Steps

```bash
1. uhhh idk
2.I really suck at coding so idk
3.see if theres anything stopping it
...
```

**Comment by untuned** [comment]
This isn't an issue with the theme, it might be a combination of plugins you're using.
