### ISSUE TITLE
[Feature Request] Allow For Transparent Background

### ISSUE THREAD

**Issue by NewAlexGamer** [ClearVision/ClearVision-v6#99]
### Did You Search Other Suggestions?

- [X] I have checked if this feature request exists already

### Is your feature request related to a problem?

yes, i have 2 monitors and like many people i like using the second one for discord and watching videos and such, with the transparent background it would be possible to watch something in the background while discord is on top of it

### Screenshots and/or description of the feature request.

i've seen someone trying for transparent discord looking through the issues, but it's not currently possible because of the import url, so actually implementing the possibility for the transparent background would be cool

### Why does the theme need this?

see related problem

**Comment by NyxIsBad** [comment]
Denying this request on the grounds that the transparency addon still works completely fine lol

**Comment by NyxIsBad** [comment]
For more information, check the pins of #support in our discord server. It's relatively easy to add and requires a BD toggle along with the import `@import url(https://mentalscars.github.io/Patch/transparency.css);`. It also works for Powercord. We don't support other injectors for our own sanity
